config/routes.rb
Rails.application.routes.draw do


    mount Ckeditor::Engine => '/ckeditor'
    root 'home#welcome'


    devise_for :users

    resources :grammars

    namespace :new_word do
        resources :verb_forms
        resources :adj_forms
    end

    resources :examples
    resources :lessons

    resources :new_words do
        collection do
            get 'sort/:lesson', action: :sort, as: 'sort'
            get 'search'
        end
    end

    resources :verbs, only: [:index]

    resources :kanjis do
        collection do
            get 'sort'
            get 'search_by_entry_number'
        end
        member do
            get :components, :references
        end
    end

    resources :kanji_components
end

app/views/shared/headers/_header_grammar.html.erb
<% if user_signed_in? %>
    <%= link_to 'New Grammar', new_grammar_path, class: "item"%>
<% end %>

app/views/shared/headers/_header_kanji.html.erb
<% if user_signed_in? %>
    <%= link_to 'New Kanji', new_kanji_path, class: "item" %>
<% end %>

app/views/shared/headers/_header_new_word.html.erb
<div class="item">
    <%= form_tag search_new_words_path, method: :get, remote: :true, class: 'ui icon input' do %>
        <%= search_field_tag 'word', nil, placeholder: 'search for words', class: 'search words' %>
        <i class="search icon"></i>
    <% end %>
</div>
<div class="ui dropdown item">
    <div class="default text">Bài học</div>
    <i class="dropdown icon"></i>
    <div class="menu" style="overflow:auto;max-height:500px;">
        <% marugoto_books.each do |book| %>
            <%=  link_to book.select_label, sort_new_words_path(lesson: book), remote: true, class: 'item' %>
        <% end %>
    </div>
</div>
<% if user_signed_in? %>
    <%= link_to 'New Word', new_new_word_path, remote: true, class: "item" %>
<% end %>

app/views/shared/headers/_main_left_header.html.erb
<%= link_to "Home", root_path, class: "header active item"  %>
<%= link_to "512 Kanji", kanjis_path, class: "item"  %>
<%= link_to "Marugoto Grammars", grammars_path, class: 'item' %>
<%= link_to "Marugoto Words", new_words_path, class: "item"  %>
<div class="ui secondary menu">
    <div class="ui dropdown item">
        <i class="angle down icon"></i>
        <div class="menu">
            <%= link_to 'Verbs', verbs_path, class: 'item' %>
        </div>
    </div>
</div>