config/routes.rb
Rails.application.routes.draw do


    mount Ckeditor::Engine => '/ckeditor'
    root 'home#welcome'


    devise_for :users

    resources :grammars

    namespace :new_word do
        resources :verb_forms
        resources :adj_forms
    end

    resources :examples
    resources :lessons

    resources :new_words do
        collection do
            get 'sort/:lesson', action: :sort, as: 'sort'
            get 'search'
        end
    end

    resources :verbs, only: [:index]

    resources :kanjis do
        collection do
            get 'sort'
            get 'search_by_entry_number'
        end
        member do
            get :components, :references
        end
    end

    resources :kanji_components
end

app/models/grammar.rb
class Grammar < ApplicationRecord

    belongs_to :lesson
    counter_culture :lesson
    has_many :examples, as: :examplable

    accepts_nested_attributes_for :examples, allow_destroy: true

    validates :title, :explanation, presence: true

end

app/controllers/grammars_controller.rb
class GrammarsController < ApplicationController
    include ApplicationHelper

    before_action :set_grammar, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

    # GET /grammars
    def index
        #@grammars = Grammar.all.includes(:lesson).sort_by{ |g| g.lesson.lesson_order }.group_by(&:lesson_id)
        @grammars = Grammar.all.includes(:lesson).order('Lessons.lesson_order').group_by(&:lesson_id)

        # ^ same results, the second is a little bit faster !
    end

    # GET /grammars/1
    # GET /grammars/1.json
    def show
    end

    # GET /grammars/new
    def new
        @grammar = Grammar.new(lesson_id: default_marugoto_lesson)
    end

    # GET /grammars/1/edit
    def edit
    end

    # POST /grammars

    def create
        @grammar = Grammar.new(grammar_params)
        cache_marugoto_lesson(@grammar.lesson_id)
        if @grammar.save
            redirect_to @grammar, flash: {success: 'Grammar was successfully created.'}
        else
            render :new
        end
    end

    # PATCH/PUT /grammars/1

    def update
        if @grammar.update(grammar_params)
            redirect_to @grammar, flash: {success: 'Grammar was successfully updated.'}
        else
            render :edit
        end
    end

    # DELETE /grammars/1

    def destroy
        @grammar.destroy
        redirect_to grammars_url, notice: 'Grammar was successfully destroyed.'
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_grammar
        @grammar = Grammar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grammar_params
        params.require(:grammar).permit(:title, :explanation, :note, :lesson_id, examples_attributes: [:id, :_destroy, :sentences, :kanji_version, :meaning, :note])
    end
end

app/helpers/grammars_helper.rb
module GrammarsHelper
end

app/views/grammars/_example_fields.html.erb
<div class="ui green segment nested-fields">
    <div class="ui grid">
        <div class="two wide column">
            <%= link_to_remove_association 'Xóa ví dụ', f, class: 'ui negative basic button' %>
        </div>
        <div class="fourteen wide column">
            <div class="two fields">
                <%= f.input :sentences, as: :ckeditor, input_html: { ckeditor: {height: 50, toolbar: 'example'} } %>
                <%= f.input :kanji_version, as: :ckeditor, input_html: { ckeditor: {height: 50, toolbar: 'example'} } %>
            </div>
            <%= f.input :meaning %>
            <%= f.input :note, as: :ckeditor, input_html: {ckeditor: { height: 100, toolbar: 'example_note' } } %>
        </div>
    </div>
</div>

app/views/grammars/_examples_list.html.erb
<table class="ui celled unstackable table">
    <tbody>
        <tr>
            <td>
                <h3 class="bigger-font"><%= example.sentences.html_safe %></h3>
            </td>
        </tr>
        <% if example.kanji_version.presence %>
            <tr>
                <td>
                    <h3><%= example.kanji_version.html_safe %></h3>
                </td>
            </tr>
        <% end %>
        <tr>
            <td>
                <h3><%= example.meaning %></h3>
            </td>
        </tr>
        <% if example.note.presence %>
            <tr>
                <td colspan="2">
                    <%= example.note.html_safe %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/grammars/_form.html.erb
<%= simple_form_for(@grammar) do |f| %>
    <div class="form-inputs">
        <%= f.input :title, as: :text, input_html: { rows: 2 }, class: 'multilines ' %>
        <%= f.input :explanation %>
        <%= f.input :note, as: :ckeditor %>
        <%= f.association :lesson, label_method: :select_label, value_method: :id, collection: Lesson.marugoto_books %>
    </div>
    <div class="ui horizontal divider">
        Ví dụ
    </div>
    <div class="examples">
        <%= f.simple_fields_for :examples do |example| %>
            <%= render 'example_fields', f: example %>
        <% end %>
        <%= link_to_add_association 'Thêm ví dụ', f, :examples, class: 'ui green button' %>
    </div>
    <div class="ui divider"></div>
    <div class="form-actions">
        <%= f.button :submit %>
        <%= link_to 'Back', grammars_path, class: 'ui button negative' %>
    </div>
<% end %>

app/views/grammars/edit.html.erb
<div class="ui container">
    <h1>Editing Grammar</h1>
    <%= render 'form', grammar: @grammar %>
</div>

app/views/grammars/index.html.erb
<div class="ui container">
    <table class="ui celled padded unstackable structured table">
        <thead>
            <tr>
                <th class="one wide center aligned">Lesson</th>
                <th class="six wide center aligned">Title</th>
                <th class="seven wide center aligned">Explanation</th>
                <% if user_signed_in? %>
                    <th colspan="2" class="two wide center aligned"></th>
                <% end %>
            </tr>
        </thead>
        <tbody>
            <% @grammars.each do |lesson_id, grammars| %>
                <% grammars.each do |grammar| %>
                    <tr>
                        <% if grammar == grammars.first %>
                            <td rowspan="<%= grammars.count %>"><%= grammar.lesson.select_short_label %></td>
                        <% end %>
                        <td>
                            <div class="bigger-font">
                                <%= link_to simple_format(grammar.title), grammar %>
                            </div>
                        </td>
                        <td>
                            <div class="bigger-font">
                                <%= grammar.explanation %>
                            </div>
                        </td>
                        <% if user_signed_in? %>
                            <td>
                                <%= link_to edit_grammar_path(grammar) , class: 'ui circular icon button' do %>
                                    <i class="edit icon"></i>
                                <% end %>
                            </td>
                            <td>
                                <%= link_to grammar, method: :delete, data: { confirm: 'Are you sure?' }, class: 'ui circular icon button' do %>
                                    <i class="delete icon"></i>
                                <% end %>
                            </td>
                        <% end %>
                    </tr>
                <% end %>
            <% end %>
        </tbody>
    </table>
</div>

app/views/grammars/new.html.erb
<div class="ui container">
    <h1>New Grammar</h1>
    <%= render 'form', grammar: @grammar %>
</div>

app/views/grammars/show.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8">
            <div class="ui biggest-font red">
                <%= simple_format @grammar.title %>
            </div>
            <h2 class="ui biggest-font">
                <%= @grammar.explanation %>
            </h2>
            <div class="ui horizontal divider">
                <p>
                    <strong>Lesson:</strong>
                    <%= @grammar.lesson.select_label %>
                </p>
            </div>
            <% if @grammar.note.presence %>
                <div class="ui segment">
                    <%= @grammar.note.html_safe %>
                </div>
            <% end %>
        </div>
        <div class="col-md-4">
            <% if user_signed_in? %>
                <div class="ui buttons">
                    <%= link_to 'Edit', edit_grammar_path(@grammar), class: 'ui positive button' %>
                    <div class="or"></div>
                    <%= link_to 'Back', grammars_path, class: 'ui button' %>
                </div>
            <% end %>
            <% if @grammar.examples.any? %>
                <div class="ui horizontal divider">
                    Ví dụ
    </div>
                <% @grammar.examples.each do |example| %>
                    <%= render partial: 'examples_list', locals: { example: example } %>
                <% end %>
            <% end %>
        </div>
    </div>
</div>