config/routes.rb
Rails.application.routes.draw do


    mount Ckeditor::Engine => '/ckeditor'
    root 'home#welcome'


    devise_for :users

    resources :grammars

    namespace :new_word do
        resources :verb_forms
        resources :adj_forms
    end

    resources :examples
    resources :lessons

    resources :new_words do
        collection do
            get 'sort/:lesson', action: :sort, as: 'sort'
            get 'search'
        end
    end

    resources :verbs, only: [:index]

    resources :kanjis do
        collection do
            get 'sort'
            get 'search_by_entry_number'
        end
        member do
            get :components, :references
        end
    end

    resources :kanji_components
end

app/models/example.rb
class Example < ApplicationRecord

    belongs_to :examplable, polymorphic: true, optional: true

    validates_presence_of :sentences, :meaning

end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
    before_action :set_example, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

    # GET /examples
    # GET /examples.json
    def index
        @examples = Example.all
    end

    # GET /examples/1
    # GET /examples/1.json
    def show
    end

    # GET /examples/new
    def new
        @example = Example.new
    end

    # GET /examples/1/edit
    def edit
    end

    # POST /examples
    # POST /examples.json
    def create
        @example = Example.new(example_params)

        respond_to do |format|
            if @example.save
                format.html { redirect_to @example, notice: 'Example was successfully created.' }
                format.json { render :show, status: :created, location: @example }
            else
                format.html { render :new }
                format.json { render json: @example.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /examples/1
    # PATCH/PUT /examples/1.json
    def update
        respond_to do |format|
            if @example.update(example_params)
                format.html { redirect_to @example, notice: 'Example was successfully updated.' }
                format.json { render :show, status: :ok, location: @example }
            else
                format.html { render :edit }
                format.json { render json: @example.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /examples/1
    # DELETE /examples/1.json
    def destroy
        @example.destroy
        respond_to do |format|
            format.html { redirect_to examples_url, notice: 'Example was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_example
        @example = Example.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def example_params
        params.fetch(:example, {})
    end
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/views/examples/_example.html.erb
<table class="ui celled table">
    <tbody>
        <tr>
            <td>
                <h3 class="bigger-font"><%= example.sentences %></h3>
            </td>
            <td>
                <h3 class="bigger-font"><%= example.kanji_version %></h3>
            </td>
        </tr>
        <tr>
            <td colspan="2" >
                <h3><%= example.meaning %></h3>
            </td>
        </tr>
        <% if example.note.presence %>
            <tr>
                <td colspan="2" >
                    <%= example.note %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/examples/_example_of_kanji.html.erb
<table class="ui celled table">
    <tbody>
        <tr>
            <td class="eight wide">
                <h3"><%= example.sentences %></h3>
            </td>
            <td class="eight wide">
                <h3"><%= example.kanji_version %></h3>
            </td>
        </tr>
        <tr>
            <td colspan="2" >
                <h3><%= example.meaning %></h3>
            </td>
        </tr>
        <% if example.note.presence %>
            <tr>
                <td colspan="2" >
                    <%= example.note %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/examples/_form.html.erb
<%= form_for(example) do |f| %>
  <% if example.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(example.errors.count, "error") %> prohibited this example from being saved:</h2>

      <ul>
      <% example.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/examples/edit.html.erb
<h1>Editing Example</h1>

<%= render 'form', example: @example %>

<%= link_to 'Show', @example %> |
<%= link_to 'Back', examples_path %>

app/views/examples/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Examples</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @examples.each do |example| %>
      <tr>
        <td><%= link_to 'Show', example %></td>
        <td><%= link_to 'Edit', edit_example_path(example) %></td>
        <td><%= link_to 'Destroy', example, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Example', new_example_path %>

app/views/examples/new.html.erb
<h1>New Example</h1>

<%= render 'form', example: @example %>

<%= link_to 'Back', examples_path %>

app/views/examples/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_example_path(@example) %> |
<%= link_to 'Back', examples_path %>